config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :channels, only: [:new, :create, :show]

  get 'channels/search' => 'channels#search', as: :search_channel
  get 'channels/:id/playlist' => 'channels#playlist', as: :channel_playlist
  post 'channels/:id/add' => 'channels#add_video', as: :add_video
  post 'channels/:id/:video_id/upvote' => 'channels#upvote_video', as: :upvote_video
  post 'channels/:id/:video_id/downvote' => 'channels#downvote_video', as: :downvote_video
  post 'channels/:id/:video_id/unvote' => 'channels#unvote_video', as: :unvote_video
  get 'channels/:id/play' => 'channels#play_video', as: :play_video
  post 'channels/:id/next' => 'channels#next_video', as: :next_video
  get 'channels/:id/search' => 'channels#search_video', as: :search_video
  delete 'channels/:id/:video_id' => 'channels#remove_video', as: :remove_video

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :slug

  belongs_to :user
  has_many :videos, dependent: :destroy, after_add: :check_active

  def active_video
    videos.where(active: true).first
  end

  def playlist
    videos.where(active: nil, played_at: nil).order("cached_weighted_score DESC")
  end

  def history(limit=nil)
    videos.where(active: false).where.not(played_at: nil).order("played_at DESC").limit(limit)
  end

  def play_next_video
    active_video.update(active: false) if active_video
    next_video = playlist.first
    next_video.update(active: true, played_at: DateTime.now) if next_video
  end

  def check_active(video)
    play_next_video if active_video.nil?
  end

  def slug_candidates
    [
      :title,
      [:title, :id]
    ]
  end

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :channels, dependent: :destroy
  has_many :videos, dependent: :nullify

  acts_as_voter

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
  belongs_to :channel

  validates_presence_of :uid, :channel

  acts_as_votable

  def link
    "http://youtu.be/#{uid}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_or_guest_user

  GOOGLE_DEVELOPER_KEY = 'AIzaSyDuWWnA6PpRvikyEwny-v93kWeHqK6DJ2E'

  after_filter :flash_to_headers

  # if user is logged in, return current_user, else return guest_user
  def current_or_guest_user
    if current_user
      if session[:guest_user_id]
        logging_in
        guest_user.destroy
        session[:guest_user_id] = nil
      end
      current_user
    else
      guest_user
    end
  end

  # find guest_user object associated with the current session,
  # creating one as needed
  def guest_user
    # Cache the value the first time it's gotten.
    @cached_guest_user ||= User.find(session[:guest_user_id] ||= create_guest_user.id)

  rescue ActiveRecord::RecordNotFound # if session[:guest_user_id] invalid
     session[:guest_user_id] = nil
     guest_user
  end

  private

  # called (once) when the user logs in, insert any code your application needs
  # to hand off from guest_user to current_user.
  def logging_in
    # For example:
    # guest_comments = guest_user.comments.all
    # guest_comments.each do |comment|
      # comment.user_id = current_user.id
      # comment.save!
    # end
  end

  def create_guest_user
    guest = User.create(email: "guest_#{Time.now.to_i}#{rand(100)}@vidj.co", guest: true)
    guest.save!(validate: false)
    session[:guest_user_id] = guest.id
    guest
  end

  def flash_to_headers
    if request.xhr?
      #avoiding XSS injections via flash
      flash_json = Hash[flash.map{|k,v| [k,ERB::Util.h(v)] }].to_json
      response.headers['X-Flash-Messages'] = flash_json
      flash.discard
    end
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :get_channel, except: [:new, :create]

  def new
    @channel = Channel.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @channel }
    end
  end

  def create
    @channel = current_or_guest_user.channels.build(channel_params)
    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, :notice => 'Channel was successfully created.' }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def search
    if @channel
      format.html { redirect_to @channel }
    else
      format.html { redirect_to root_url, :notice => 'Channel does not exist.' }
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def destroy
    respond_to do |format|
      format.html { redirect_to root_path }
    end
  end

  def add_video
    active = @channel.active_video
    @video = @channel.videos.create(title: params[:title], uid: params[:uid], user: current_or_guest_user)
    respond_to do |format|
      format.html { redirect_to @channel }
      format.js {
        flash[:success] = "#{@video.title} was added to the playlist"
        if active != @channel.active_video
          render action: "broadcast_update_active_video"
        else
          render action: "broadcast_update_playlist"
        end
      }
    end
  end

  def remove_video
    video = Video.find(params[:video_id])
    video.destroy

    respond_to do |format|
      format.html { redirect_to @channel }
      format.js { render action: "broadcast_update_playlist" }
    end
  end

  def upvote_video
    video = Video.find(params[:video_id])

    video.liked_by current_or_guest_user
    respond_to do |format|
      format.html { redirect_to @channel }
      format.js { render action: "broadcast_update_playlist" }
    end
  end

  def unvote_video
    video = Video.find(params[:video_id])

    video.unliked_by current_or_guest_user
    respond_to do |format|
      format.html { redirect_to @channel }
      format.js { render action: "broadcast_update_playlist" }
    end
  end

  def search_video
    load_google_api
    opts = {
      q: params[:q],
      type: :video,
      videoEmbeddable: "true",
      part: "id,snippet"
    }
    response = @client.execute!(api_method: @youtube.search.list, parameters: opts)
    @search_results = []
    response.data.items.each do |item|
      @search_results.push Video.new title: item.snippet.title, uid: item.id.videoId
    end
    logger.debug @search_results
    respond_to do |format|
      format.js {}
    end
  end

  def playlist
  end

  def play_video
    respond_to do |format|
      format.js { }
    end
  end

  def next_video
    @channel.play_next_video
    flash[:notice] = "#{@channel.active_video.title} started playing" if @channel.active_video
    respond_to do |format|
      format.js { render action: "broadcast_update_active_video" }
    end
  end

  private

  def get_channel
    @channel = Channel.friendly.find(params[:id])
  end

  def load_google_api
    @client = Google::APIClient.new key: GOOGLE_DEVELOPER_KEY, application_name: 'VIDJ', application_version: '0.0.1', authorization: nil
    @youtube = @client.discovered_api('youtube', 'v3')
  end

  def channel_params
    params.require(:channel).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_active_video.html.erb
<% if @channel.active_video %>
  <div class="video" data-uid="<%= @channel.active_video.uid %>">
    <blockquote>
      <p>
        Now playing<br />
        <strong><%= @channel.active_video.title %></strong>
      </p>
      <footer><%= link_to @channel.active_video.link, @channel.active_video.link, target: "_blank" %></footer>
    </blockquote>
  </div>
<% else %>
  <blockquote>
    <p>No active video</p>
  </blockquote>
<% end %>

app/views/channels/_play_video.js.erb
if($("#channel").hasClass("synced")) {
  <% if @channel.active_video %>
    channel.loadVideo("<%= @channel.active_video.uid %>", <%= @channel.active_video.played_at.utc.to_i * 1000 %>)
    $("#player-wrapper").slideDown()
  <% else %>
    $("#player-wrapper").slideUp(400, function() {
      channel.ytplayer.stopVideo()
    })
  <% end %>
}
$("#active-video > .content").html("<%= j (render partial: 'active_video') %>")

app/views/channels/_player_controls.html.erb
<%= link_to play_video_path, remote: true, method: :get, class: "btn btn-success btn-play" do %>
  <span class="glyphicon glyphicon-film"></span> Sync
<% end %>

<%= link_to '#', class: "btn btn-danger btn-stop" do %>
  <span class="glyphicon glyphicon-off"></span> Stop
<% end %>

<% if @channel.user == current_or_guest_user %>
  <%= link_to next_video_path, remote: true, method: :post, class: "btn btn-default btn-next" do %>
    <span class="glyphicon glyphicon-step-forward"></span> Next
  <% end %>
<% end %>

app/views/channels/_search_result.html.erb
<li class="list-group-item">
  <div class="video">
    <div class="image">
      <%= image_tag "https://img.youtube.com/vi/#{video.uid}/default.jpg" %>
    </div>
    <div class="text">
      <%= form_tag(add_video_path(@channel), remote: true, method: :post) do %>
        <%= hidden_field_tag :uid, video.uid %>
        <%= hidden_field_tag :title, video.title %>
        <%= button_tag type: :submit, class: "btn btn-link" do %>
          <%= video.title %>
        <% end %>
      <% end %>
    </div>
  </div>
</li>

app/views/channels/_video.html.erb
<li class="list-group-item">
  <div class="video">
    <div class="image">
      <%= image_tag "https://img.youtube.com/vi/#{video.uid}/default.jpg" %>
    </div>
    <div class="text">
      <div class="pull-left">
        <%= link_to video.title, video.link, class: "btn btn-link", target: '_blank' %>
      </div>
      <div class="pull-right">
        <span class="badge"><%= video.cached_weighted_score %></span>
        <% if current_or_guest_user.liked? video %>
          <%= link_to unvote_video_path(video.channel, video), class: "btn btn-default active", remote: true, method: :post do %>
            <span class="glyphicon glyphicon-chevron-up"></span>
          <% end %>
        <% else %>
          <%= link_to upvote_video_path(video.channel, video), class: "btn btn-default", remote: true, method: :post do %>
            <span class="glyphicon glyphicon-chevron-up"></span>
          <% end %>
        <% end %>
        <% if current_or_guest_user == video.user || current_or_guest_user == video.channel.user %>
          <%= link_to remove_video_path(video.channel, video), class: "btn btn-default", remote: true, method: :delete do %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
        <% end %>
      </div>
    </div>
</li>

app/views/channels/broadcast_update_active_video.js.erb
<% publish_to "/channels/#{@channel.slug}" do %>
  channel.updateActiveVideo()
  channel.updatePlaylist()
<% end %>

app/views/channels/broadcast_update_playlist.js.erb
<% publish_to "/channels/#{@channel.slug}" do %>
  channel.updatePlaylist()
<% end %>

app/views/channels/new.html.erb
<h2>Create your channel</h2>
<div class="well">
  <%= simple_form_for @channel do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.button :submit, class: "btn-primary" %>
  <% end %>
</div>

app/views/channels/play_video.js.erb
<%= render partial: 'play_video' %>

app/views/channels/playlist.js.erb
$("#playlist").html("<%= j (render partial: 'video', collection: @channel.playlist) %>")

app/views/channels/search_video.js.erb
$("#search-results .content").html("<%= j (render partial: 'search_result', collection: @search_results, as: :video) %>").parents('#search-results').slideDown()

app/views/channels/show.html.erb
<%= subscribe_to "/channels/#{@channel.slug}" %>
<%= javascript_include_tag "https://www.youtube.com/iframe_api" %>

<div id="channel" class="<%= @channel.user == current_or_guest_user ? 'admin' : 'visitor' %>">
  <div id="channel-info" class="row">
    <div class="col-xs-12">
      <h1><%= @channel.title %></h1>
      <div class="lead"><%= simple_format(@channel.description) %></div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">

      <div id="player-wrapper" class="embed-responsive embed-responsive-16by9">
        <div id="player" class="embed-responsive-item" data-url="<%= play_video_path %>"></div>
      </div>

      <div id="active-video-wrapper" class="row">
        <div class="col-xs-12">
          <div id="active-video">
            <div class="content">
              <%= render partial: "active_video" %>
            </div>
            <div id="player-controls">
              <div class="content">
                <%= render partial: "player_controls" %>
              </div>
            </div>
          </div>
          <br />
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div id="search-wrapper" class="row">
        <div class="col-xs-12">
          <div class="well">
            <%= form_tag(search_video_path, remote: true, method: :get) do %>
            <div class="input-group">
              <%= search_field_tag :q, nil, class: "form-control" %>
              <span class="input-group-btn">
                <%= button_tag type: :submit, class: "btn btn-default" do %>
                <span class="glyphicon glyphicon-search"></span>
                <% end %>
              </span>
            </div>
            <% end %>
            <div id="search-results">
              <br />
              <div class="content list-group"></div>
              <div class="text-center">
                <%= link_to "#", onclick: 'channel.hideSearchResults()', class:"small" do %>
                hide results
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="playlist-wrapper" class="row">
        <div class="col-xs-12">
          <h3>Playlist</h3>
          <ul id="playlist" class="list-group" data-url="<%= channel_playlist_path %>"></ul>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:page_title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/home.html.erb
<%= content_for :page_title, 'VIDJ - crowdsource your playlist' %>


<h1>VIDJ</h1>
<p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mattis justo vitae justo bibendum, sit amet rhoncus erat viverra. Proin at dui ut lacus pretium imperdiet. Mauris ut lectus facilisis, eleifend felis pellentesque, commodo augue. Donec nec dictum velit. Nulla luctus metus a luctus ornare. Phasellus id ex fermentum, mattis enim in, efficitur quam.</p>
<%= link_to "Create a new channel", new_channel_path, class: "btn btn-primary" %>